
package techquizapp.gui;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import techquizapp.pojo.AnswerStore;
import techquizapp.dao.PerformanceDAO;
import techquizapp.dao.QuestionDAO;
import techquizapp.pojo.QuestionStore;
import techquizapp.pojo.Answer;
import techquizapp.pojo.Exam;
import techquizapp.pojo.Performance;
import techquizapp.pojo.Question;
import techquizapp.pojo.UserProfile;

public class TakeTestFrame extends javax.swing.JFrame {
    Exam newEx ;
    QuestionStore qstore ;
    AnswerStore astore ;
    private int qno,pos=0,qNoForTimer;
    public TakeTestFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Tech-Quiz Application");
        qstore = new QuestionStore();
        astore = new AnswerStore();
        qno=1;
        lblCurrQues.setText("Question "+qno);
    }
    public TakeTestFrame(Exam ex){
        this();
        newEx = ex;
        qNoForTimer = ex.getNoOFQuestions();
        SetTimer st = new SetTimer();
        st.start();
        lblSetSubjectName.setText(newEx.getLanguage().toUpperCase()+" PAPER");
        loadQuestions();
        showQuestion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupOption = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCurrQues = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQues = new javax.swing.JTextArea();
        jrbOption1 = new javax.swing.JRadioButton();
        jrbOption3 = new javax.swing.JRadioButton();
        jrbOption4 = new javax.swing.JRadioButton();
        jrbOption2 = new javax.swing.JRadioButton();
        btnnNext = new javax.swing.JButton();
        btnnCancel = new javax.swing.JButton();
        btnnDone = new javax.swing.JButton();
        btnnPrevious = new javax.swing.JButton();
        lblSetSubjectName = new javax.swing.JLabel();
        lblCurrQues1 = new javax.swing.JLabel();
        lblCurrQues2 = new javax.swing.JLabel();
        lblCurrQues3 = new javax.swing.JLabel();
        lblCurrQues4 = new javax.swing.JLabel();
        lblSetTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblCurrQues.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCurrQues.setForeground(new java.awt.Color(204, 255, 255));
        lblCurrQues.setText("Question : 1");

        txtQues.setColumns(20);
        txtQues.setRows(5);
        jScrollPane1.setViewportView(txtQues);

        jrbOption1.setBackground(new java.awt.Color(51, 51, 51));
        btnGroupOption.add(jrbOption1);
        jrbOption1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOption1.setForeground(new java.awt.Color(204, 255, 255));
        jrbOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOption1ActionPerformed(evt);
            }
        });

        jrbOption3.setBackground(new java.awt.Color(51, 51, 51));
        btnGroupOption.add(jrbOption3);
        jrbOption3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOption3.setForeground(new java.awt.Color(204, 255, 255));

        jrbOption4.setBackground(new java.awt.Color(51, 51, 51));
        btnGroupOption.add(jrbOption4);
        jrbOption4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOption4.setForeground(new java.awt.Color(204, 255, 255));

        jrbOption2.setBackground(new java.awt.Color(51, 51, 51));
        btnGroupOption.add(jrbOption2);
        jrbOption2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOption2.setForeground(new java.awt.Color(204, 255, 255));

        btnnNext.setBackground(new java.awt.Color(0, 0, 0));
        btnnNext.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        btnnNext.setForeground(new java.awt.Color(204, 204, 204));
        btnnNext.setText("Next");
        btnnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnNextActionPerformed(evt);
            }
        });

        btnnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnnCancel.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        btnnCancel.setForeground(new java.awt.Color(204, 204, 204));
        btnnCancel.setText("Cancel");
        btnnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnCancelActionPerformed(evt);
            }
        });

        btnnDone.setBackground(new java.awt.Color(0, 0, 0));
        btnnDone.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        btnnDone.setForeground(new java.awt.Color(204, 204, 204));
        btnnDone.setText("Done");
        btnnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnDoneActionPerformed(evt);
            }
        });

        btnnPrevious.setBackground(new java.awt.Color(0, 0, 0));
        btnnPrevious.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        btnnPrevious.setForeground(new java.awt.Color(204, 204, 204));
        btnnPrevious.setText("Previous");
        btnnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnPreviousActionPerformed(evt);
            }
        });

        lblSetSubjectName.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblSetSubjectName.setForeground(new java.awt.Color(153, 255, 204));
        lblSetSubjectName.setText("QUESTIONS REMAINING");

        lblCurrQues1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCurrQues1.setForeground(new java.awt.Color(204, 255, 255));
        lblCurrQues1.setText("A.");

        lblCurrQues2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCurrQues2.setForeground(new java.awt.Color(204, 255, 255));
        lblCurrQues2.setText("B.");

        lblCurrQues3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCurrQues3.setForeground(new java.awt.Color(204, 255, 255));
        lblCurrQues3.setText("C.");

        lblCurrQues4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCurrQues4.setForeground(new java.awt.Color(204, 255, 255));
        lblCurrQues4.setText("C.");

        lblSetTimer.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblSetTimer.setForeground(new java.awt.Color(204, 255, 255));
        lblSetTimer.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblCurrQues)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCurrQues1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurrQues2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurrQues3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurrQues4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(btnnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jrbOption4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrbOption3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrbOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jrbOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(lblSetSubjectName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(lblSetTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSetTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblSetSubjectName)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrQues))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbOption1)
                            .addComponent(lblCurrQues1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbOption2)
                            .addComponent(lblCurrQues2))
                        .addGap(18, 18, 18)
                        .addComponent(jrbOption3))
                    .addComponent(lblCurrQues3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbOption4)
                    .addComponent(lblCurrQues4))
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnCancel)
                    .addComponent(btnnDone)
                    .addComponent(btnnPrevious)
                    .addComponent(btnnNext))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnNextActionPerformed
       String chosenAnswer = getUserAnswer();
       if(chosenAnswer!=null){
           Question  question = qstore.getQuestionByQno(qno); System.out.println(question);
           String correctAnswer = question.getCorrectAns(); 
           Answer newAnswer = new Answer(newEx.getLanguage(),newEx.getExamId(),chosenAnswer,correctAnswer,qno);
           System.out.println(newAnswer);
           Answer answer = astore.getAnswerByQno(qno);
            if(answer==null){
                astore.addAnswer(newAnswer);
            }
            else{
                if(newAnswer.getChosenAnswer().equals(answer.getCorrectAnswer())==false){
                    int apos = astore.removeAnswer(answer);
                    astore.setAnswerAt(apos, newAnswer);
                }
            }
        }
       
       pos++;
        System.out.println("Pos "+pos+"  qstore.getCount +"+qstore.getCount());
        if(pos>=qstore.getCount()){
            pos=0;
        }
        qno++;
        
        if(qno>qstore.getCount()){
            qno=1;
        }
        lblCurrQues.setText("Question no."+qno);
        showQuestion();
    }//GEN-LAST:event_btnnNextActionPerformed

    private void jrbOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOption1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbOption1ActionPerformed

    private void btnnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnCancelActionPerformed
           PaperSelection paperSelectFrame = new PaperSelection();
           paperSelectFrame.setVisible(true);
           this.dispose();     
    }//GEN-LAST:event_btnnCancelActionPerformed

    private void btnnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnDoneActionPerformed
        DoneBtn();
    }//GEN-LAST:event_btnnDoneActionPerformed

    private void btnnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnPreviousActionPerformed
       String chosenAnswer = getUserAnswer();
       if(chosenAnswer!=null){
           Question  question = qstore.getQuestionByQno(qno);  System.out.println(question);
           String correctAnswer = question.getCorrectAns();
           Answer newAnswer = new Answer(newEx.getLanguage(),newEx.getExamId(),chosenAnswer,correctAnswer,qno);
           System.out.println(newAnswer);
           Answer answer = astore.getAnswerByQno(qno);
            if(answer==null){
                astore.addAnswer(newAnswer);
            }
            else{
                if(newAnswer.getChosenAnswer().equals(answer.getCorrectAnswer())==false){
                    int apos = astore.removeAnswer(answer);
                    astore.setAnswerAt(apos, newAnswer);
                }
            }
        }
       pos--;
        if(pos<0){
            pos=qstore.getCount()-1;
        }
        
        qno--;
        if(qno<=0){
            qno=qstore.getCount();
        }
        lblCurrQues.setText("Question no."+qno);
        showQuestion();
    }//GEN-LAST:event_btnnPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeTestFrame().setVisible(true);
            }
        });
    }
    public String getUserAnswer(){
        if(jrbOption1.isSelected())
            return "Answer1";
        else if(jrbOption2.isSelected())
            return "Answer2";
        else if(jrbOption3.isSelected())
            return "Answer3";
        else if(jrbOption4.isSelected())
            return "Answer4";
        else 
            return null;
    }
    public void loadQuestions(){
        try {
            ArrayList<Question> questionList = QuestionDAO.getQuestionsByExamId(newEx.getExamId());
            for(Question ques : questionList){
                qstore.addQuestion(ques);
            }
           }
         catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error in Fetching All Questions from DB ","Exception", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
           }
      } 
    public void showQuestion (){
        Question ques = qstore.getQuestion(pos);
        btnGroupOption.clearSelection();
        txtQues.setText(ques.getQuestion());
        jrbOption1.setText(ques.getAnswer1());
        jrbOption2.setText(ques.getAnswer2());
        jrbOption3.setText(ques.getAnswer3());
        jrbOption4.setText(ques.getAnswer4());
        
        Answer ans = astore.getAnswerByQno(qno);
        if(ans==null)
            return ;
        String chosenAnswer = ans.getChosenAnswer();
        switch(chosenAnswer){
            case "Answer1" : jrbOption1.setSelected(true);
                             break;
            case "Answer2" : jrbOption2.setSelected(true);
                             break;
            case "Answer3" : jrbOption3.setSelected(true);
                             break;
            case "Answer4" : jrbOption4.setSelected(true);
                             break;                 
        }
    }
    class SetTimer extends Thread{
        public void run(){
         try {
             int totaltime,hr,min,sec;
             int q = qNoForTimer; System.out.println("Q :  "+q);
             totaltime = q*60;
            while(true){
                    min = totaltime/60;
                    sec = totaltime - min*60;
                    hr = totaltime/(60*60); 
                    if(min>60)
                        min = min/60;
                    totaltime--;
                    lblSetTimer.setText("Time Left :- "+hr+":"+min+":"+sec);
                    Thread.sleep(1000);
                   if(hr==0&& min==0 &&sec==0) 
                       DoneBtn();
                } 
             }
          catch (InterruptedException ex) {
                    JOptionPane.showMessageDialog(null," Problem in Setting Timer ","Exception ! ",JOptionPane.ERROR_MESSAGE);
                    return;
                }
        }
    }
    public void DoneBtn(){
         String userAnswer = getUserAnswer();
        if(userAnswer!=null){
            Question question = qstore.getQuestionByQno(qno);
            String correctAnswer = question.getCorrectAns();
            Answer newAnswer = new Answer(newEx.getLanguage(),newEx.getExamId(),userAnswer,correctAnswer,qno);
            System.out.println(newAnswer);
             Answer answer = astore.getAnswerByQno(qno);
           if(answer==null){
                astore.addAnswer(newAnswer);
            }
            else{
                if(newAnswer.getChosenAnswer().equals(answer.getChosenAnswer())==false){
                    int apos = astore.removeAnswer(answer);
                    astore.setAnswerAt(apos, newAnswer);
                   }
                }
         } 
        int right=0 ,wrong=0;
        for(Question ques : qstore.getAllQuestions()){
            int qno = ques.getNoOfQuestion();
            Answer answer =  astore.getAnswerByQno(qno);
            if(answer==null)
                continue;
            else{
                String chosenAns = answer.getChosenAnswer();
                String correctAns = answer.getCorrectAnswer();
                if(chosenAns.equals(correctAns))
                    ++right;
                else ++wrong;
            }
         }
        String reportCard = "Total Qustions : "+qstore.getCount();
        reportCard += "\n Right Answer : "+right;
        reportCard += "\n Wrong Answer : "+wrong;
        reportCard += "\n UnAtempted : "+(qstore.getCount()-(wrong+right));
        JOptionPane.showMessageDialog(null,reportCard,"Your Result",JOptionPane.INFORMATION_MESSAGE);
      try {  
           Performance perFor = new Performance(UserProfile.getUsername(),newEx.getExamId(),newEx.getLanguage(),right,wrong,(qstore.getCount()-(wrong+right)),(double)right/qstore.getCount()*100);
           PerformanceDAO.addPerformance(perFor);
           PaperSelection paperSelectFrame = new PaperSelection();
           paperSelectFrame.setVisible(true);
           this.dispose();
        } 
      catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"Problem in Sending Performance  to DB ","Exception !",JOptionPane.ERROR_MESSAGE);
           ex.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"Your Performnace has been Successfully sent to DataBase","Success",JOptionPane.INFORMATION_MESSAGE);
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupOption;
    private javax.swing.JButton btnnCancel;
    private javax.swing.JButton btnnDone;
    private javax.swing.JButton btnnNext;
    private javax.swing.JButton btnnPrevious;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbOption1;
    private javax.swing.JRadioButton jrbOption2;
    private javax.swing.JRadioButton jrbOption3;
    private javax.swing.JRadioButton jrbOption4;
    private javax.swing.JLabel lblCurrQues;
    private javax.swing.JLabel lblCurrQues1;
    private javax.swing.JLabel lblCurrQues2;
    private javax.swing.JLabel lblCurrQues3;
    private javax.swing.JLabel lblCurrQues4;
    private javax.swing.JLabel lblSetSubjectName;
    private javax.swing.JLabel lblSetTimer;
    private javax.swing.JTextArea txtQues;
    // End of variables declaration//GEN-END:variables
}
